name: CI/CD Pipeline

on:
  push:
    branches: [ main ]   # or your default branch name
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt  # adjust path if needed

    - name: Run tests
      run: |
        python manage.py test  # Adjust to your test command

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Add deployment steps here, e.g., deploy to Kubernetes or cloud provider
    - name: Deploy to Kubernetes
      run: |
        echo "Add your deployment commands here"
